#!/usr/bin/env bash
# pg-sync render —— 两种产物：
#   render.sh bundle <pg-sync.env> <输出目录>          生产侧 bundle：脚本 + 独立 env（人 scp 上生产机执行；ADR-0001）
#   render.sh dev <脚本名> <pg-sync.env> <输出路径>     dev 侧自包含内联脚本（含内嵌 lib.sh，人 scp 上 dev 机执行）
# <脚本名> ∈ receive-setup | fetch-oss | restore-schema | restore-data
set -euo pipefail
umask 077   # 产物可能含贴入的公钥，写入期间即收紧权限（收尾 chmod 是补收尾，不补窗口期）

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"   # -P 解软链，skills 是软链装的（setup.sh）
PROD_DIR="${HERE}/prod"
DEV_DIR="${HERE}/dev"
LIB="${HERE}/lib.sh"
TPL_PROD_ENV="${HERE}/../templates/prod-env.example"
TPL_REPORT="${HERE}/../templates/sync-report.md"

usage_die() {
    echo "problem: 用法错误" >&2
    echo "cause: 第一个参数只能是 bundle 或 dev" >&2
    echo "fix: render.sh bundle <pg-sync.env> <输出目录>  或  render.sh dev <脚本名> <pg-sync.env> <输出路径>" >&2
    exit 1
}

KIND="${1:-}"
[[ "${KIND}" == "bundle" || "${KIND}" == "dev" ]] || usage_die

# ==== bundle：生产侧目录 ==============================================================
if [[ "${KIND}" == "bundle" ]]; then
    ENV_FILE="${2:?用法: render.sh bundle <pg-sync.env> <输出目录>}"
    OUT_DIR="${3:?用法: render.sh bundle <pg-sync.env> <输出目录>}"
    [[ -r "${ENV_FILE}" ]] || { echo "problem: 读不到 ${ENV_FILE}" >&2; exit 1; }
    [[ -r "${TPL_PROD_ENV}" ]] || { echo "problem: 找不到 ${TPL_PROD_ENV}" >&2; exit 1; }
    command -v perl >/dev/null || { echo "problem: 缺 perl（渲染模板需要）" >&2; exit 1; }

    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    : "${DB_NAME:?pg-sync.env 里 DB_NAME 必填}"
    DATA_RULES="${DATA_RULES:-* full}"
    NICE="${NICE:-19}"
    IONICE="${IONICE:--c3}"
    LOCK_WAIT_TIMEOUT="${LOCK_WAIT_TIMEOUT:-30s}"
    RSYNC_DEST_HOST="${RSYNC_DEST_HOST:-}"
    RSYNC_DEST_USER="${RSYNC_DEST_USER:-pgsync}"
    RSYNC_DEST_DIR="${RSYNC_DEST_DIR:-}"
    RSYNC_DEST_HOSTKEY="${RSYNC_DEST_HOSTKEY:-}"
    OSS_BUCKET="${OSS_BUCKET:-}"
    OSS_PREFIX="${OSS_PREFIX:-}"
    OSS_ENDPOINT_UPLOAD="${OSS_ENDPOINT_UPLOAD:-}"

    mkdir -p "${OUT_DIR}"
    chmod 700 "${OUT_DIR}"

    cp "${LIB}" "${OUT_DIR}/lib.sh"
    for f in "${PROD_DIR}"/*.sh; do
        cp "${f}" "${OUT_DIR}/$(basename "${f}")"
    done
    chmod 700 "${OUT_DIR}"/*.sh

    PROD_ENV_OUT="${OUT_DIR}/pg-sync-prod.env"
    if [[ -e "${PROD_ENV_OUT}" ]]; then
        echo "[*] ${PROD_ENV_OUT} 已存在，跳过（不覆盖生产机上人已填的值：EXPECT_SYSID / EXPECT_HOSTNAME / DUMP_DIR 等）"
    else
        export SRC_DB="${DB_NAME}" DATA_RULES NICE IONICE LOCK_WAIT_TIMEOUT \
               RSYNC_DEST_HOST RSYNC_DEST_USER RSYNC_DEST_DIR RSYNC_DEST_HOSTKEY \
               OSS_BUCKET OSS_PREFIX OSS_ENDPOINT_UPLOAD
        perl -pe 's/\{\{(\w+)\}\}/exists $ENV{$1} ? $ENV{$1} : ""/ge' "${TPL_PROD_ENV}" > "${PROD_ENV_OUT}"
        chmod 600 "${PROD_ENV_OUT}"
        echo "[✓] ${PROD_ENV_OUT} 已生成（EXPECT_SYSID / EXPECT_HOSTNAME / DUMP_DIR 留空，人在生产机上填）"
    fi

    echo "已生成 bundle：${OUT_DIR}（权限 700）——下一步：scp -r ${OUT_DIR} <生产机>:/tmp/pg-sync/"
    exit 0
fi

# ==== dev：自包含内联脚本 ===============================================================
NAME="${2:?用法: render.sh dev <脚本名> <pg-sync.env> <输出路径>}"
case "${NAME}" in
    receive-setup|fetch-oss|restore-schema|restore-data) ;;
    *)
        echo "problem: 脚本名不认识（当前: ${NAME}）" >&2
        echo "cause: dev 侧只有 receive-setup / fetch-oss / restore-schema / restore-data 四个脚本" >&2
        echo "fix: 检查拼写" >&2
        exit 1
        ;;
esac
ENV_FILE="${3:?用法: render.sh dev <脚本名> <pg-sync.env> <输出路径>}"
OUT="${4:?用法: render.sh dev <脚本名> <pg-sync.env> <输出路径>}"
BODY="${DEV_DIR}/${NAME}.sh"
[[ -r "${ENV_FILE}" ]] || { echo "problem: 读不到 ${ENV_FILE}" >&2; exit 1; }
[[ -r "${BODY}" ]] || { echo "problem: 找不到 ${BODY}" >&2; exit 1; }
[[ -r "${LIB}" ]] || { echo "problem: 找不到 ${LIB}" >&2; exit 1; }
[[ -r "${TPL_REPORT}" ]] || { echo "problem: 找不到 ${TPL_REPORT}" >&2; exit 1; }

mkdir -p "$(dirname "${OUT}")"
{
    echo '#!/usr/bin/env bash'
    echo "# generated by pg-ops/pg-sync $(date '+%F %T') from $(basename "${ENV_FILE}") —— 可能含贴入的公钥，用完即删"
    echo 'PG_OPS_RENDERED=1'
    echo 'umask 077'
    echo '# ---- 参数（来自 env）----'
    grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "${ENV_FILE}"
    echo '# ---- lib.sh 正文（内嵌）----'
    tail -n +2 "${LIB}"          # 去掉本体自己的 shebang
    echo '# ---- 同步报告模板（base64）----'
    echo "PG_OPS_REPORT_TPL_B64='$(base64 < "${TPL_REPORT}" | tr -d '\n')'"
    echo '# ---- 脚本本体 ----'
    tail -n +2 "${BODY}"          # 去掉本体自己的 shebang
} > "${OUT}"
chmod 700 "${OUT}"
echo "已生成 ${OUT}（权限 700）"
