#!/usr/bin/env bash
# 把 env 参数 + 交接文档模板 + 脚本本体渲染成一份自包含脚本，人 scp 上服务器 sudo bash 即可。
# 用法：render.sh <env 文件> <输出路径> [install|harden]   缺省 install
set -euo pipefail
umask 077   # 产物含口令，写入期间即 700（收尾的 chmod 700 只是补收尾，不补窗口期）
ENV_FILE="${1:?用法: render.sh <env 文件> <输出路径>}"
OUT="${2:?用法: render.sh <env 文件> <输出路径>}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"   # -P 解析软链，skills 是软链装的（setup.sh），逻辑路径下 ../../pg-ops-shared 不可达
KIND="${3:-install}"
case "${KIND}" in
    install) BODY="${HERE}/install-ubuntu.sh" ;;
    harden)  BODY="${HERE}/harden-ubuntu.sh" ;;
    *) echo "problem: 第三个参数只能是 install 或 harden（当前: ${KIND}）" >&2; exit 1 ;;
esac
TPL="${HERE}/../templates/handover.md"
DIAG_DIR="${HERE}/../../pg-ops-shared/diag"
[[ -r "${ENV_FILE}" ]] || { echo "problem: 读不到 ${ENV_FILE}" >&2; exit 1; }
[[ -d "${DIAG_DIR}" ]] || {
    echo "problem: 找不到 ${DIAG_DIR}" >&2
    echo "cause: 运行 checkout 不完整（Windows 未拷 pg-ops-shared/）或目录被删" >&2
    echo "fix: 重跑 setup.sh 或检查运行 checkout" >&2
    exit 1
}
mkdir -p "$(dirname "${OUT}")"
{
    echo '#!/usr/bin/env bash'
    echo "# generated by pg-ops/pg-dev-server $(date '+%F %T') from $(basename "${ENV_FILE}") —— 可能含口令，用完即删"
    echo 'PG_OPS_RENDERED=1'
    echo '# ---- 参数（来自 env）----'
    grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "${ENV_FILE}"
    echo '# ---- 交接文档模板（base64）----'
    echo "PG_OPS_TEMPLATE_B64='$(base64 < "${TPL}" | tr -d '\n')'"
    echo '# ---- 诊断脚本包（tar.gz + base64）----'
    echo "PG_OPS_DIAG_TGZ_B64='$(tar czf - -C "$(dirname "${DIAG_DIR}")" "$(basename "${DIAG_DIR}")" | base64 | tr -d '\n')'"
    echo '# ---- 脚本本体 ----'
    tail -n +2 "${BODY}"          # 去掉本体自己的 shebang
} > "${OUT}"
chmod 700 "${OUT}"
echo "已生成 ${OUT}（权限 700）"
