#!/usr/bin/env bash
# 把 env 参数 + 交接文档模板 + 脚本本体渲染成一份自包含脚本，人 scp 上服务器 sudo bash 即可。
# 用法：render.sh <env 文件> <输出路径>
set -euo pipefail
umask 077
ENV_FILE="${1:?用法: render.sh <env 文件> <输出路径>}"
OUT="${2:?用法: render.sh <env 文件> <输出路径>}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BODY="${HERE}/provision.sh"
TPL="${HERE}/../templates/project.md"
[[ -r "${ENV_FILE}" ]] || { echo "problem: 读不到 ${ENV_FILE}" >&2; exit 1; }
# 本机预检：直接跑脚本本体的 env 校验段（守卫①）。参数错在这里就停，省掉
# 「render 成功 -> scp -> ssh -> 到服务器才发现库名非法」那一整轮往返（B8）。
# 校验逻辑只在 provision.sh 一处，此处只调用、不复制。
PG_OPS_VALIDATE_ONLY=1 bash "${BODY}" "${ENV_FILE}" >/dev/null || {
    echo "fix: 修正 ${ENV_FILE} 后重跑 render.sh；未生成 ${OUT}" >&2
    exit 1
}
mkdir -p "$(dirname "${OUT}")"
{
    echo '#!/usr/bin/env bash'
    echo "# generated by pg-ops/pg-dev-init $(date '+%F %T') from $(basename "${ENV_FILE}") —— 可能含口令，用完即删"
    echo 'PG_OPS_RENDERED=1'
    echo '# ---- 参数（来自 env）----'
    grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "${ENV_FILE}"
    echo '# ---- 交接文档模板（base64）----'
    echo "PG_OPS_TEMPLATE_B64='$(base64 < "${TPL}" | tr -d '\n')'"
    echo '# ---- 脚本本体 ----'
    tail -n +2 "${BODY}"          # 去掉本体自己的 shebang
} > "${OUT}"
chmod 700 "${OUT}"
echo "已生成 ${OUT}（权限 700）"
